# Generated by Django 4.2.7 on 2026-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_ae', '0002_noonorder_raw_data_noonorderitem_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noonorder',
            name='customer_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='geo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='order_total',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='shipping_information',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='Fulfillment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='Pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='ProductDetails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='PromotionDiscount',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='TaxCollection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='listing_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='product_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
