# Generated by Django 4.2.7 on 2026-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noon_ae', '0003_noonorder_customer_order_id_noonorder_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noonorder',
            name='automated_shipping_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='is_business_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='is_premium_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='items_order_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='marketplace_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='number_of_items_shipped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='number_of_items_unshipped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonorder',
            name='shipping_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='IsGift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonorderitem',
            name='Platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='a_shipping_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='channel_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='cogs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='marketplace_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='pack_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='page_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='product_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='referral_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='refund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='sessions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='total_cogs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='variant_group_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='noonproduct',
            name='wpid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
