# Generated by Django 4.2.7 on 2026-01-28 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_order_id', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Unshipped', 'Unshipped'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=20)),
                ('fulfillment_channel', models.CharField(default='MFN', max_length=10)),
                ('sales_channel', models.CharField(default='Amazon.ae', max_length=50)),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total_currency', models.CharField(default='AED', max_length=3)),
                ('number_of_items_shipped', models.IntegerField(default=0)),
                ('number_of_items_unshipped', models.IntegerField(default=0)),
                ('payment_method', models.CharField(default='Other', max_length=50)),
                ('marketplace_id', models.CharField(default='A2VIGQ35RCS4UG', max_length=50)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('ship_service_level', models.CharField(blank=True, max_length=100)),
                ('earliest_ship_date', models.DateTimeField(blank=True, null=True)),
                ('latest_ship_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default='', max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=50, unique=True)),
                ('asin', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_shipped', models.IntegerField(default=0)),
                ('item_price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_price_currency', models.CharField(default='AED', max_length=3)),
                ('shipping_price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promotion_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('condition_id', models.CharField(default='New', max_length=50)),
                ('is_gift', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='amazon_ae.amazonorder')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('fn_sku', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('condition', models.CharField(default='new', max_length=50)),
                ('available_quantity', models.IntegerField(default=0)),
                ('pending_quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('warehouse_condition_code', models.CharField(blank=True, max_length=50)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sku')},
            },
        ),
    ]
