# Generated by Django 4.2.7 on 2026-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
