# Generated by Django 4.2.7 on 2026-02-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ae', '0002_amazonorder_raw_data_amazonorderitem_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='customer_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='geo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='order_total',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='shipping_information',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='listing_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='referral_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='total_cogs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='wpid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
