# Generated by Django 4.2.7 on 2026-02-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_ae', '0003_amazonorder_customer_order_id_amazonorder_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='automated_shipping_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='is_business_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonorder',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='Fulfillment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='Platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='Pricing',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='ProductDetails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='PromotionDiscount',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='TaxCollection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonorderitem',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='a_shipping_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='channel_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='cogs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='fullfillment_by_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='fullfillment_by_channel_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='marketplace_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='pack_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='page_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='refund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='sessions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='variant_group_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='will_ship_internationally',
            field=models.BooleanField(default=False),
        ),
    ]
